# Introduction to Linear Algebra

---

## 1. What is Linear Algebra?
Linear algebra is the branch of mathematics that deals with **vectors**, **matrices**, and **linear transformations**. It is foundational to machine learning and is used in:

- **Data Representation:** Data is often represented as vectors (for individual data points) or matrices (for datasets).
- **Transformations:** Linear algebra is used to rotate, scale, and project data.
- **Algorithms:** Techniques like Principal Component Analysis (PCA), Singular Value Decomposition (SVD), and neural networks rely heavily on linear algebra.

---

## 2. Scalars, Vectors, and Matrices

### 2.1. Scalars
A **scalar** is a single number (e.g., 5, -3.2, π). Scalars are used to represent quantities like weights, biases, and learning rates in machine learning.

### 2.2. Vectors
A **vector** is an ordered list of numbers. For example:

$
\mathbf{v} = \begin{bmatrix} 1 \\ 2 \\ 3 \end{bmatrix}
$

<br>

In [58]:
# Python way
v = [1, 2, 3]

# NumPy way
import numpy as np
v = np.array([1, 2, 3])

<br>
Vectors are used to represent data points, features, or model parameters. They are often denoted with lowercase bold letters (e.g., **v**).

### 2.3. Matrices
A **matrix** is a 2D array of numbers. For example:

$
\mathbf{A} = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}
$

<br>

In [59]:
# Python way
A = [[1, 2], [3, 4]]

# NumPy way
A = np.array([[1, 2], [3, 4]])

<br>
Matrices are used to represent datasets, transformations, and weights in neural networks. They are often denoted with uppercase bold letters (e.g. **A**)

---

## 3. Basic Operations

### Vector Addition and Substraction
Vectors of the same size can be added or subtracted element-wise:

$
\mathbf{u} + \mathbf{v} = \begin{bmatrix} u_1 + v_1 \\ u_2 + v_2 \\ \vdots \\ u_n + v_n \end{bmatrix}
$

<br>

In [60]:
# Python way
u = [1, 2, 3]
v = [4, 5, 6]
vector_sum = [u[i] + v[i] for i in range(len(u))]

# NumPy way:
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
vector_sum = u + v

print("Vector Addition:", vector_sum)

Vector Addition: [5 7 9]


<br>

### Scalar Multiplication
A vector can be multiplied by a scalar, scaling each element:

$
c \cdot \mathbf{v} = \begin{bmatrix} c \cdot v_1 \\ c \cdot v_2 \\ \vdots \\ c \cdot v_n \end{bmatrix}
$

<br>

In [61]:
# Python way
c = 2
v = [1, 2, 3]
scalar_mult = [c * v_i for v_i in v]

# NumPy way
c = 2
v = np.array([1, 2, 3])
scalar_mult = c * v

print("Scalar Multiplication:", scalar_mult)

Scalar Multiplication: [2 4 6]


<br>

### Matrix Addition and Subtraction
Matrices of the same size can be added or subtracted element-wise:

$
\mathbf{A} + \mathbf{B} = \begin{bmatrix} a_{11} + b_{11} & a_{12} + b_{12} \\ a_{21} + b_{21} & a_{22} + b_{22} \end{bmatrix}
$

<br>

In [62]:
# Python way
A = [[1, 2],
     [3, 4]]
B = [[5, 6], 
     [7, 8]]
matrix_sum = [[A[i][j] + B[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# NumPy way
A = np.array([[1, 2], 
              [3, 4]])
B = np.array([[5, 6], 
              [7, 8]])
matrix_sum = A + B

print("Matrix Addition:\n", matrix_sum)

Matrix Addition:
 [[ 6  8]
 [10 12]]


<br>

### Scalar Multiplication of Matrices
A matrix can be multiplied by a scalar, scaling each element.

$
c \cdot \mathbf{A} = \begin{bmatrix} c \cdot a_{11} & c \cdot a_{12} \\ c \cdot a_{21} & c \cdot a_{22} \end{bmatrix}
$

<br>

In [63]:
# Python way
c = 2
A = [[1, 2],
     [3, 4]]
scalar_mult = [[c * A[i][j] for j in range(len(A[0]))] for i in range(len(A))]

# NumPy way
c = 2
A = np.array([[1, 2],
              [3, 4]])
scalar_mult = c * A

print("Scalar Multiplication of Matrix:\n", scalar_mult)

Scalar Multiplication of Matrix:
 [[2 4]
 [6 8]]



---

## Real-World Example: Feature Representation in a Dataset
In machine learning, datasets are often represented as matrices, where:
* **Rows** represent individual data points (samples).
* **Columns** represent features (attributes) of the data.

Let's consider a dataset of house prices with the following features:
1. Size (in square meters)
2. Number of bedrooms
3. Age of the house (in years)

### Dataset
We can represent this dataset as matrix:

$
\mathbf{X} = \begin{bmatrix}
150 & 3 & 10 \\
120 & 2 & 20 \\
200 & 4 & 5 \\
\end{bmatrix}
$

Here: 
* Each row corresponds to a house.
* Each column corresponds to a feature (Size, Bedrooms, Age).

#### Python Implementation
We can represent this dataset in Python using NumPy:

In [64]:
import numpy as np

# Dataset of house features: [Size, Bedrooms, Age]
X = np.array([
    [150, 3, 10],
    [120, 2, 20],
    [200, 4, 5]
], dtype=float)

print("House Features Dataset:\n", X)

House Features Dataset:
 [[150.   3.  10.]
 [120.   2.  20.]
 [200.   4.   5.]]


<br>

### Scaling Features
In machine learning, it's common to scale features so that they have similar ranges. For example, we can scale the **Size** feature to be in the range [0, 1] and the **Age** feature to be in the range [0, 100].

#### Scaling Formula:
For a feature \( x \), the scaled value \( x_{\text{scaled}} \) is calculated as:

$
x_{\text{scaled}} = \frac{x - x_{\text{min}}}{x_{\text{max}} - x_{\text{min}}}
$

#### Python Implementation

In [65]:
# Scale the Size feature (column 0)
size_min = X[:, 0].min()
size_max = X[:, 0].max()
X[:, 0] = (X[:, 0] - size_min) / (size_max - size_min)

# Scale the Age feature (column 2)
age_min = X[:, 2].min()
age_max = X[:, 2].max()
X[:, 2] = (X[:, 2] - age_min) / (age_max - age_min)

print("Scaled House Features Dataset:\n", X)

Scaled House Features Dataset:
 [[0.375      3.         0.33333333]
 [0.         2.         1.        ]
 [1.         4.         0.        ]]


## Summary of Lesson 1
- **Linear algebra** is essential for machine learning.
- **Scalars**, **vectors**, and **matrices** are the building blocks of linear algebra.
- Scalars represent single values like weights and biases.
- Vectors represent data points or features.
- Matrices represent datasets or transformations.
- Basic operations include addition, subtraction, and scalar multiplication.
- These concepts are implemented in Python using both plain Python and NumPy.