# Lineer Cebire Giriş

---

## 1. Lineer Cebir Nedir? 

**Lineer cebir** (_linear algebra_), **vektörler** (_vectors_), **matrisler** (_matrices_) ve **lineer dönüşümler** (_linear transformations_) gibi matematiksel yapıları inceleyen bir matematik dalıdır. Temelde, doğrusal denklemlerin çözümü (_solving systems of linear equations_) ve bu denklemlerle ifade edilebilen sistemlerin analizi ile ilgilenir.

### Veri Biliminde Lineer Cebirin Önemi

Lineer cebir **veri bilimi** (_data science_) ve **makine öğrenmesi** (_machine learning_) alanlarında şu işlevlere sahiptir: 

1. **Veri Temsili (_Data Representation_):** Veri bilimi projelerinde elimizdeki veriler genellikle sayılardan oluşur. Bu sayıları düzenli bir şekilde ifade etmek için **vektörler** ve **matrisler** kullanılır. Örneğin, bir evin büyüklüğü, oda sayısı, konumu gibi özellikleri bir vektör ile, birden fazla evin özelliklerini ise bir matris ile gösterebiliriz.

2. **Model Oluşturma (_Model Building_):** Makine öğrenmesi algoritmaları, veriler arasındaki ilişkileri modellemek için lineer cebir kavramlarını kullanır. Örneğin, **lineer regresyon** (_linear regression_), **lojistik regresyon** (_logistic regression_), **destek vektör makineleri** (_support vector machines_) gibi birçok algoritmanın temelinde lineer cebir yatar.

3. **Boyut Azaltma (_Dimensionality Reduction_):** Veri setlerimiz bazen çok sayıda özellik içerebilir. Bu durum, hem hesaplama maliyetini artırır hem de modelin performansını düşürebilir. **Temel Bileşen Analizi** (_Principal Component Analysis, PCA_) gibi boyut azaltma teknikleri, lineer cebir sayesinde veriyi daha az sayıda, ama daha anlamlı özelliklerle ifade etmemizi sağlar.

4.  **Derin Öğrenme (_Deep Learning_):** Günümüzde popüler olan **derin öğrenme** algoritmaları, yapay sinir ağlarından (_neural networks_) oluşur. Bu ağlardaki işlemler, aslında matris çarpımları ve lineer dönüşümlerden başka bir şey değildir.
<br><br>
---

## 2. Skalerler, Vektörler ve Matrisler (Scalars, Vectors, and Matrices)
Lineer cebirin temel yapı taşları olan skalerler, vektörler ve matrisleri sırayla inceleyelim:

### 2.1. Skalerler (*Scalars*)
**Skaler**, tek bir sayıdan oluşan bir niceliktir. Matematikte ve fizikte sıklıkla kullanılır. Örneğin, sıcaklık, kütle, zaman gibi değerler birer skalerdir.

#### Matematiksel Gösterim
Skalerler genellikle küçük harflerle ifade edilir (örneğin, *a*, *b*, *x*, *y*).

#### Python'da Skalerler
Python'da skalerler, `int`, `float` gibi sayısal veri tipleriyle temsil edilir.

In [6]:
a = 5       # int (tamsayı)
b = -3.14   # float (ondalıklı sayı)

### 2.2. Vektörler (*Vectors*)
**Vektör**, sıralı bir sayı dizisidir.  Tek bir boyutta (yani tek bir sütun veya satırda) birden fazla sayıyı temsil eder. Vektörler, hem yönü hem de büyüklüğü olan nicelikleri ifade etmek için kullanılır (fizikteki hız, kuvvet gibi). Veri biliminde ise genellikle bir veri noktasının özelliklerini temsil ederler.

Vektörler genellikle kalın küçük harflerle veya üzerine ok işareti konularak gösterilir. Vektörün elemanları ise köşeli parantez içinde, virgüllerle ayrılarak yazılır.

$ \mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix} $ (sütun vektörü) veya $ \mathbf{v} = \begin{bmatrix} v_1 & v_2 & \dots & v_n \end{bmatrix} $ (satır vektörü)


Örneğin bir öğrencinin sınav notları:

$\mathbf{v} = \begin{bmatrix} 85 \\ 92 \\ 78 \end{bmatrix}$

olarak gösterilebilir. Aynı vektörü Python'da şu şekilde ifade edebiliriz:

In [7]:
import numpy as np

v = np.array([85, 92, 78])
print(v)

[85 92 78]


### 2.3. Matrisler (*Matrices*)
**Matrisler**, iki boyutlu bir sayı dizisidir. Birden fazla satır ve sütundan oluşur. Matrisler, makine öğrenmesinde veri setlerini (*datasets*) temsil etmek için kullanılır. Her satır bir veri noktasını (*data point*), her sütun bir özelliği (*feature*) temsil eder.

Matrisler genellikle büyük harflerle gösterilir (örneğin, **A**, **B**, **X**). Elemanları ise `aᵢⱼ` şeklinde gösterilir; burada *i* satır numarasını, *j* ise sütun numarasını belirtir.

$
\mathbf{A} = \begin{bmatrix}
a_{1,1} & a_{1,2} & \dots & a_{1,n} \\
a_{2,1} & a_{2,2} & \dots & a_{2,n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m,1} & a_{m,2} & \dots & a_{m,n}
\end{bmatrix}
$

**Örnek:** Birden fazla evin özelliklerini bir matrisle ifade etmek istediğimizi düşünelim. Bu matrisi matematiksel olarak şöyle gösterebiliriz:

$
\mathbf{X} = \begin{bmatrix}
150 & 3 & 10 \\
120 & 2 & 20 \\
200 & 4 & 5
\end{bmatrix}
$

Python'da matrisler de NumPy kütüphanesindeki `array` veri yapısıyla temsil edilir.

In [8]:
import numpy as np

X = np.array([
    [150, 3, 10],  # Ev 1: Alan, Oda Sayısı, Yaş
    [120, 2, 20],  # Ev 2
    [200, 4, 5]    # Ev 3
])
print(X)

[[150   3  10]
 [120   2  20]
 [200   4   5]]
