# Lineer Cebire Giriş

---

## 1. Lineer Cebir Nedir? 

**Lineer cebir** (_linear algebra_), **vektörler** (_vectors_), **matrisler** (_matrices_) ve **lineer dönüşümler** (_linear transformations_) gibi matematiksel yapıları inceleyen bir matematik dalıdır. Temelde, doğrusal denklemlerin çözümü (_solving systems of linear equations_) ve bu denklemlerle ifade edilebilen sistemlerin analizi ile ilgilenir.

### Veri Biliminde Lineer Cebirin Önemi

Lineer cebir **veri bilimi** (_data science_) ve **makine öğrenmesi** (_machine learning_) alanlarında şu işlevlere sahiptir: 

1. **Veri Temsili (_Data Representation_):** Veri bilimi projelerinde elimizdeki veriler genellikle sayılardan oluşur. Bu sayıları düzenli bir şekilde ifade etmek için **vektörler** ve **matrisler** kullanılır. Örneğin, bir evin büyüklüğü, oda sayısı, konumu gibi özellikleri bir vektör ile, birden fazla evin özelliklerini ise bir matris ile gösterebiliriz.

2. **Model Oluşturma (_Model Building_):** Makine öğrenmesi algoritmaları, veriler arasındaki ilişkileri modellemek için lineer cebir kavramlarını kullanır. Örneğin, **lineer regresyon** (_linear regression_), **lojistik regresyon** (_logistic regression_), **destek vektör makineleri** (_support vector machines_) gibi birçok algoritmanın temelinde lineer cebir yatar.

3. **Boyut Azaltma (_Dimensionality Reduction_):** Veri setlerimiz bazen çok sayıda özellik içerebilir. Bu durum, hem hesaplama maliyetini artırır hem de modelin performansını düşürebilir. **Temel Bileşen Analizi** (_Principal Component Analysis, PCA_) gibi boyut azaltma teknikleri, lineer cebir sayesinde veriyi daha az sayıda, ama daha anlamlı özelliklerle ifade etmemizi sağlar.

4.  **Derin Öğrenme (_Deep Learning_):** Günümüzde popüler olan **derin öğrenme** algoritmaları, yapay sinir ağlarından (_neural networks_) oluşur. Bu ağlardaki işlemler, aslında matris çarpımları ve lineer dönüşümlerden başka bir şey değildir.
<br><br>
---

## 2. Skalerler, Vektörler ve Matrisler (Scalars, Vectors, and Matrices)
Lineer cebirin temel yapı taşları olan skalerler, vektörler ve matrisleri sırayla inceleyelim:

### 2.1. Skalerler (*Scalars*)
**Skaler**, tek bir sayıdan oluşan bir niceliktir. Matematikte ve fizikte sıklıkla kullanılır. Örneğin, sıcaklık, kütle, zaman gibi değerler birer skalerdir. Skalerler genellikle küçük harflerle ifade edilir (örneğin, *a*, *b*, *x*, *y*).

Python'da ise skalerler, `int`, `float` gibi sayısal veri tipleriyle temsil edilir.

In [28]:
a = 5       # int (tamsayı)
b = -3.14   # float (ondalıklı sayı)

### 2.2. Vektörler (*Vectors*)
**Vektör**, sıralı bir sayı dizisidir.  Tek bir boyutta (yani tek bir sütun veya satırda) birden fazla sayıyı temsil eder. Vektörler, hem yönü hem de büyüklüğü olan nicelikleri ifade etmek için kullanılır (fizikteki hız, kuvvet gibi). Veri biliminde ise genellikle bir veri noktasının özelliklerini temsil ederler.

Vektörler genellikle kalın küçük harflerle veya üzerine ok işareti konularak gösterilir. Vektörün elemanları ise köşeli parantez içinde, virgüllerle ayrılarak yazılır.

$ \mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix} $ (sütun vektörü) veya $ \mathbf{v} = \begin{bmatrix} v_1 & v_2 & \dots & v_n \end{bmatrix} $ (satır vektörü)

**Örnek:** bir öğrencinin sınav notları:

$\mathbf{v} = \begin{bmatrix} 85 \\ 92 \\ 78 \end{bmatrix}$

olarak gösterilebilir. Aynı vektörü Python'da şu şekilde ifade edebiliriz:

In [29]:
import numpy as np

v = np.array([85, 92, 78])
print(v)

[85 92 78]


### 2.3. Matrisler (*Matrices*)
**Matrisler**, iki boyutlu bir sayı dizisidir. Birden fazla satır ve sütundan oluşur. Matrisler, makine öğrenmesinde veri setlerini (*datasets*) temsil etmek için kullanılır. Her satır bir veri noktasını (*data point*), her sütun bir özelliği (*feature*) temsil eder.

Matrisler genellikle büyük harflerle gösterilir (örneğin, **A**, **B**, **X**). Elemanları ise `aᵢⱼ` şeklinde gösterilir; burada *i* satır numarasını, *j* ise sütun numarasını belirtir.

$
\mathbf{A} = \begin{bmatrix}
a_{1,1} & a_{1,2} & \dots & a_{1,n} \\
a_{2,1} & a_{2,2} & \dots & a_{2,n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m,1} & a_{m,2} & \dots & a_{m,n}
\end{bmatrix}
$

**Örnek:** Birden fazla evin özelliklerini (metrekare cinsinden büyüklüğünü, oda sayısını, yaşını) bir matrisle ifade etmek istediğimizi düşünelim. Bu matrisi matematiksel olarak şöyle gösterebiliriz:

$
\mathbf{X} = \begin{bmatrix}
150 & 3 & 10 \\
120 & 2 & 20 \\
200 & 4 & 5
\end{bmatrix}
$

Python'da matrisler de NumPy kütüphanesindeki `array` veri yapısıyla temsil edilir.

In [30]:
import numpy as np

X = np.array([
    [150, 3, 10],  # Ev 1: Alan, Oda Sayısı, Yaş
    [120, 2, 20],  # Ev 2
    [200, 4, 5]    # Ev 3
])
print(X)

[[150   3  10]
 [120   2  20]
 [200   4   5]]


---

## 3. Temel İşlemler
Skalerler, vektörler ve matrisler üzerinde çeşitli matematiksel işlemler yapabiliriz. Bu bölümde en temel işlemleri inceleyeceğiz: toplama, çıkarma ve skaler çarpım.

### 3.1. Toplama ve Çıkarma (Addition and Subtraction)

#### 3.1.1. Vektörlerde Toplama ve Çıkarma
Aynı boyuttaki iki vektörün karşılıklı elemanları toplanarak veya çıkarılarak yeni bir vektör elde edilir.

$ \mathbf{u} = \begin{bmatrix} u_1 \\ u_2 \\ \vdots \\ u_n \end{bmatrix} $,
$ \mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix} $  olsun.

$ \mathbf{u} + \mathbf{v} = \begin{bmatrix} u_1 + v_1 \\ u_2 + v_2 \\ \vdots \\ u_n + v_n \end{bmatrix} $,
$ \mathbf{u} - \mathbf{v} = \begin{bmatrix} u_1 - v_1 \\ u_2 - v_2 \\ \vdots \\ u_n - v_n \end{bmatrix} $

**Örnek:**

$ \mathbf{u} = \begin{bmatrix} 1 \\ 3 \\ 2 \end{bmatrix} $,
$ \mathbf{v} = \begin{bmatrix} 4 \\ 0 \\ -1 \end{bmatrix} $ ise,

$ \mathbf{u} + \mathbf{v} = \begin{bmatrix} 1+4 \\ 3+0 \\ 2+(-1) \end{bmatrix} = \begin{bmatrix} 5 \\ 3 \\ 1 \end{bmatrix} $,
    $ \mathbf{u} - \mathbf{v} = \begin{bmatrix} 1-4 \\ 3-0 \\ 2-(-1) \end{bmatrix} = \begin{bmatrix} -3 \\ 3 \\ 3 \end{bmatrix} $

<br>

In [31]:
import numpy as np

u = np.array([1, 3, 2])
v = np.array([4, 0, -1])

print("u + v:", u + v)
print("u - v:", u - v)

u + v: [5 3 1]
u - v: [-3  3  3]


#### 3.1.2. Matrislerde Toplama ve Çıkarma
Aynı boyutlardaki (aynı sayıda satır ve sütuna sahip) iki matrisin karşılıklı elemanları toplanarak veya çıkarılarak yeni bir matris elde edilir.

$ \mathbf{A} = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} $,
$ \mathbf{B} = \begin{bmatrix} b_{11} & b_{12} \\ b_{21} & b_{22} \end{bmatrix} $ olsun.

$ \mathbf{A} + \mathbf{B} = \begin{bmatrix} a_{11}+b_{11} & a_{12}+b_{12} \\ a_{21}+b_{21} & a_{22}+b_{22} \end{bmatrix} $,
$ \mathbf{A} - \mathbf{B} = \begin{bmatrix} a_{11}-b_{11} & a_{12}-b_{12} \\ a_{21}-b_{21} & a_{22}-b_{22} \end{bmatrix} $

**Örnek:**  

$ \mathbf{A} = \begin{bmatrix} 2 & 5 \\ 1 & 0 \end{bmatrix} $,
$ \mathbf{B} = \begin{bmatrix} -1 & 3 \\ 4 & 2 \end{bmatrix} $ ise,

$ \mathbf{A} + \mathbf{B} = \begin{bmatrix} 2+(-1) & 5+3 \\ 1+4 & 0+2 \end{bmatrix} = \begin{bmatrix} 1 & 8 \\ 5 & 2 \end{bmatrix} $,
$ \mathbf{A} - \mathbf{B} = \begin{bmatrix} 2-(-1) & 5-3 \\ 1-4 & 0-2 \end{bmatrix} = \begin{bmatrix} 3 & 2 \\ -3 & -2 \end{bmatrix} $

<br>

In [32]:
import numpy as np

A = np.array([[2, 5], [1, 0]])
B = np.array([[-1, 3], [4, 2]])

print("A + B:\n", A + B)
print("A - B:\n", A - B)

A + B:
 [[1 8]
 [5 2]]
A - B:
 [[ 3  2]
 [-3 -2]]


### 3.2. Skaler Çarpım (Scalar Multiplication)

#### 3.2.1. Vektörlerde Skaler Çarpım
Bir vektörün her elemanı, bir skaler ile çarpılarak yeni bir vektör elde edilir.

$ \mathbf{v} = \begin{bmatrix} v_1 \\ v_2 \\ \vdots \\ v_n \end{bmatrix} $ ve *c* bir skaler olsun.

$ c\mathbf{v} = \begin{bmatrix} cv_1 \\ cv_2 \\ \vdots \\ cv_n \end{bmatrix} $

**Örnek:**

$ \mathbf{v} = \begin{bmatrix} 2 \\ -1 \\ 4 \end{bmatrix} $ ve *c* = 3 ise,

$ 3\mathbf{v} = \begin{bmatrix} 3\cdot2 \\ 3\cdot(-1) \\ 3\cdot4 \end{bmatrix} = \begin{bmatrix} 6 \\ -3 \\ 12 \end{bmatrix} $

<br>

In [33]:
import numpy as np

v = np.array([2, -1, 4])
c = 3

print("c * v:", c * v)

c * v: [ 6 -3 12]


#### 3.2.2. Matrislerde Skaler Çarpım
Bir matrisin her elemanı, bir skaler ile çarpılarak yeni bir matris elde edilir.

$ \mathbf{A} = \begin{bmatrix} a_{11} & a_{12} \\ a_{21} & a_{22} \end{bmatrix} $ ve *c* bir skaler olsun.

$ c\mathbf{A} = \begin{bmatrix} c \cdot a_{11} & c \cdot a_{12} \\ c \cdot a_{21} & c \cdot a_{22} \end{bmatrix} $

**Örnek:**

$ \mathbf{A} = \begin{bmatrix} 1 & -2 \\ 3 & 4 \end{bmatrix} $ ve *c* = -2 ise,

$ -2\mathbf{A} = \begin{bmatrix} -2\cdot1 & -2\cdot(-2) \\ -2\cdot3 & -2\cdot4 \end{bmatrix} = \begin{bmatrix} -2 & 4 \\ -6 & -8 \end{bmatrix} $

<br>

In [34]:
import numpy as np

A = np.array([[1, -2], [3, 4]])
c = -2

print("c * A:\n", c * A)

c * A:
 [[-2  4]
 [-6 -8]]


---

## 4. Real-World Example: Processing Customer Data

Suppose an e-commerce company wants to analyze the purchasing habits of its customers.  We have a dataset like this:

| Customer ID | Age | Spending (€) | Number of Products Purchased |
| :--------: | :-: | :----------: | :----------------------: |
|     1      | 25  |     500      |            3             |
|     2      | 32  |     1200     |            5             |
|     3      | 41  |     850      |            2             |
|     4      | 28  |     300      |            1             |

We can represent this dataset as a matrix:

$
\mathbf{X} = \begin{bmatrix}
25 & 500 & 3 \\
32 & 1200 & 5 \\
41 & 850 & 2 \\
28 & 300 & 1
\end{bmatrix}
$

Here, each row represents a customer, and each column represents a feature (age, spending, number of products).

Now, let's perform some analyses using the basic operations we've learned:

### Average Spending
To find the average spending of customers, we can take the vector representing the "Spending (€)" column, sum its elements, and divide by the number of elements. This involves scalar multiplication and addition.

*   First, take the spending column as a vector: $\mathbf{s} = \begin{bmatrix} 500 \\ 1200 \\ 850 \\ 300 \end{bmatrix}$

*   Sum the elements of this vector: $500 + 1200 + 850 + 300 = 2850$

*   Divide the sum by the number of elements (4): $2850 / 4 = 712.5$

*   So, the average spending of customers is 712.5 TL.


In [35]:
import numpy as np

X = np.array([[25, 500, 3],
                [32, 1200, 5],
                [41, 850, 2],
                [28, 300, 1]])

spending = X[:, 1]  # Take all rows (:) and the 2nd column (index 1)
average_spending = np.mean(spending)
print("Average Spending:", average_spending)

Average Spending: 712.5


### Age Standardization
Let's say we want to standardize the ages of the customers (transform them to have a mean of 0 and a standard deviation of 1).  This can improve the performance of some machine learning algorithms.

*   First, take the age column as a vector: $\mathbf{a} = \begin{bmatrix} 25 \\ 32 \\ 41 \\ 28 \end{bmatrix}$

*   Calculate the mean of this vector: $(25 + 32 + 41 + 28) / 4 = 31.5$

*   Subtract the mean from each age: $\begin{bmatrix} 25-31.5 \\ 32-31.5 \\ 41-31.5 \\ 28-31.5 \end{bmatrix} = \begin{bmatrix} -6.5 \\ 0.5 \\ 9.5 \\ -3.5 \end{bmatrix}$

*   Calculate the standard deviation of this new vector (we'll let Python handle this for now).

*   Divide each element by the standard deviation (this is also a scalar multiplication operation).

In [36]:
import numpy as np

ages = X[:, 0]  # Take all rows and the 1st column (index 0)
mean_age = np.mean(ages)
std_dev = np.std(ages)
standardized_ages = (ages - mean_age) / std_dev
print("Standardized Ages:", standardized_ages)

Standardized Ages: [-1.07959124  0.08304548  1.57786412 -0.58131836]
