# Creating NumPy Arrays

---

### Table of Contents
1. Creating Arrays from Python Lists
2. Intrinsic Array Creation (From Scratch)
3. Creating Arrays with Ranges
4. Creating Arrays with Random Data

---

## 1. Creating Arrays from Python Lists
- The most basic way to create an array is using `np.array()` on a Python list or tuple.

In [10]:
import numpy as np

# --- 1-D Array (Vector) ---
list_1d = [1, 2, 3, 4]
array_1d = np.array(list_1d)

# --- 2-D Array (Matrix) ---
# Created from a list of lists. Note that inner lists must have the same length.
list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)

print("--- Creating Arrays from Lists ---")
print("1-D Array:\n", array_1d)
print("\n2-D Array:\n", array_2d)

--- Creating Arrays from Lists ---
1-D Array:
 [1 2 3 4]

2-D Array:
 [[1 2 3]
 [4 5 6]]



---

## 2. Intrinsic Array Creation (From Scratch)
- NumPy provides functions to create arrays without needing to start with a Python list.
- These are useful for creating arrays of a specific size and initial value.

### 2.1. Create an array of all zeros
- The argument is a tuple specifying the shape (rows, columns).

In [11]:
zeros_array = np.zeros((2, 3))  # 2 rows, 3 columns
print("Zeros array (2x3):\n", zeros_array)

Zeros array (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]


### 2.2. Create an array of all ones

In [12]:
ones_array = np.ones((3, 2))  # 3 rows, 2 columns
print("\nOnes array (3x2):\n", ones_array)


Ones array (3x2):
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


### 2.3. Create an array filled with a specific value

In [13]:
full_array = np.full((2, 4), fill_value=7)  # 2x4 array filled with 7s
print("\nFull array (2x4 with 7s):\n", full_array)


Full array (2x4 with 7s):
 [[7 7 7 7]
 [7 7 7 7]]


### 2.4. Create an identity matrix
- An identity matrix has 1s on the diagonal and 0s elsewhere.

In [14]:
identity_matrix = np.eye(3)  # A 3x3 identity matrix.
print("\nIdentity matrix (3x3):\n", identity_matrix)


Identity matrix (3x3):
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]



---

## 3. Creating Arrays with Ranges
- Functions for creating arrays with sequences of numbers.

### 3.1. `np.arange()`
- Similar to Python's built-in `range()`, but returns a NumPy array.
- Can use floating-point steps.
- Syntax: `np.arange(start, stop, step)`


In [15]:
range_array = np.arange(
    0, 10, 2
)  # Start at 0, go up to (but not including) 10, in steps of 2
print("`arange(0, 10, 2)`:\n", range_array)

`arange(0, 10, 2)`:
 [0 2 4 6 8]


### 3.2. `np.linspace()`
- Creates an array with a specified number of points, evenly spaced
  between a start and end value. The endpoint IS included.
- Syntax: `np.linspace(start, stop, num_points)`

In [16]:
linspace_array = np.linspace(0, 1, 5)  # 5 points from 0 to 1 (inclusive)
print("\n`linspace(0, 1, 5)`:\n", linspace_array)


`linspace(0, 1, 5)`:
 [0.   0.25 0.5  0.75 1.  ]



---

## 4. Creating Arrays with Random Data
- The `np.random` submodule is crucial for simulations, modeling, and machine learning.

### 4.1. Reproducibility with `np.random.seed()`
- Setting a "seed" ensures that the "random" numbers generated are the same every time the code runs. This is critical for reproducible results.

In [17]:
np.random.seed(42)

### 4.2. `np.random.rand(rows, cols)`
- Random values from a uniform distribution over [0, 1).

In [18]:
rand_array = np.random.rand(2, 3)  # A 2x3 array of random floats
print("`rand(2, 3)` (Uniform distribution):\n", rand_array)

`rand(2, 3)` (Uniform distribution):
 [[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]]


### 4.3. `np.random.randn(rows, cols)`
- Random values from the standard normal ("Gaussian") distribution (mean 0, variance 1).


In [19]:
randn_array = np.random.randn(2, 3)  # A 2x3 array of random floats from normal dist.
print("\n`randn(2, 3)` (Normal distribution):\n", randn_array)


`randn(2, 3)` (Normal distribution):
 [[ 1.57921282  0.76743473 -0.46947439]
 [ 0.54256004 -0.46341769 -0.46572975]]


### 4.4. `np.random.randint(low, high, size)`
- Random integers from `low` (inclusive) to `high` (exclusive).

In [20]:
randint_array = np.random.randint(
    0, 10, size=(3, 4)
)  # A 3x4 array of random ints from 0-9

print("\n`randint(0, 10, size=(3, 4))`:\n", randint_array)


`randint(0, 10, size=(3, 4))`:
 [[9 5 8 0]
 [9 2 6 3]
 [8 2 4 2]]



---

**Next:** [Array Attributes and Data Types](./03_array_attributes_and_dtypes.ipynb)