# Advanced Indexing

---

### Table of Contents
1. Introduction to Advanced Indexing
2. Boolean Indexing (Masking)
3. Fancy Indexing (Integer Array Indexing)
4. Reminder: Advanced Indexing Creates Copies

---

## 1. Introduction to Advanced Indexing
- Advanced indexing goes beyond simple integers and slices.
- It allows us to select elements based on complex conditions (boolean indexing)
  or specific lists of indices (fancy indexing).
- IMPORTANT: Unlike basic slicing which creates a view, advanced indexing
  always returns a *copy* of the data. Modifying the new array will not
  affect the original.

In [14]:
import numpy as np

# Create a sample array to work with
np.random.seed(42)  # seed for reproducibility
arr = np.random.randint(0, 50, size=(4, 5))  # 4x5 array of random ints from 0-49

print("--- Original Sample Array ---")
print(arr)

--- Original Sample Array ---
[[38 28 14 42  7]
 [20 38 18 22 10]
 [10 23 35 39 23]
 [ 2 21  1 23 43]]



---

## 2. Boolean Indexing (Masking)
- This is a very powerful technique for filtering data.
- You use a boolean array (a "mask") to select elements from another array.

In [15]:
# --- Step 1: Create a boolean condition ---

# This comparison is done element-wise and returns a boolean array of the same shape.
is_greater_than_20 = arr > 20

print("The boolean mask (arr > 20):\n", is_greater_than_20)

The boolean mask (arr > 20):
 [[ True  True False  True False]
 [False  True False  True False]
 [False  True  True  True  True]
 [False  True False  True  True]]


In [16]:
# --- Step 2: Use the mask to index the original array ---

# This selects only the elements where the mask is True.
print("Elements greater than 20:\n", arr[is_greater_than_20])

Elements greater than 20:
 [38 28 42 38 22 23 35 39 23 21 23 43]


In [17]:
# --- Combining boolean conditions ---

# Use bitwise operators `&` (and), `|` (or), and `~` (not).
# Note: Standard Python `and`, `or` do not work for element-wise comparisons.
print("\nElements between 10 and 30:")
between_10_and_30 = arr[(arr > 10) & (arr < 30)]
print(between_10_and_30)


Elements between 10 and 30:
[28 14 20 18 22 23 23 21 23]


In [18]:
# --- Using boolean indexing to modify values ---

# This is a very common and powerful pattern.
# Let's replace all odd numbers with -1
arr_copy = arr.copy()
arr_copy[arr_copy % 2 != 0] = -1  # Replace where condition is True
print("\nArray with odd numbers replaced by -1:\n", arr_copy)


Array with odd numbers replaced by -1:
 [[38 28 14 42 -1]
 [20 38 18 22 10]
 [10 -1 -1 -1 -1]
 [ 2 -1 -1 -1 -1]]



---

## 3. Fancy Indexing (Integer Array Indexing)
- Using lists or arrays of integers to select data.

In [19]:
# --- Fancy Indexing in 1-D ---

arr_1d = np.arange(10, 20)
indices_to_get = [1, 4, 7, 8]
print(f"Original 1-D array: {arr_1d}")
print(f"Selecting elements at indices {indices_to_get}: {arr_1d[indices_to_get]}")

Original 1-D array: [10 11 12 13 14 15 16 17 18 19]
Selecting elements at indices [1, 4, 7, 8]: [11 14 17 18]


In [20]:
# --- Fancy Indexing in 2-D ---

# Create a 16-element 1-D array and reshape it to a 4x4 2-D array
arr_2d = np.arange(16).reshape(4, 4)
print("\nOriginal 2-D array:\n", arr_2d)


Original 2-D array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [21]:
# --- Selecting specific rows ---

selected_rows = arr_2d[[0, 3]]
print("\nSelecting rows 0 and 3:\n", selected_rows)


Selecting rows 0 and 3:
 [[ 0  1  2  3]
 [12 13 14 15]]


In [22]:
# --- Selecting specific elements by coordinates ---

# To select elements at (row, col) pairs, pass a tuple of two lists/arrays:
# ([row_indices], [col_indices])
# Let's get elements at (0, 1), (2, 3), and (3, 0)
selected_elements = arr_2d[(0, 2, 3), (1, 3, 0)]
print("\nSelecting elements at (0,1), (2,3), and (3,0):", selected_elements)


Selecting elements at (0,1), (2,3), and (3,0): [ 1 11 12]



---

## 4. Reminder: Advanced Indexing Creates Copies
- Remember that boolean and fancy indexing return a copy of the data, not a view.

In [23]:
print("Original array:\n", arr)

# Get a new array using a boolean mask
bool_selection = arr[arr > 30]
print(f"\nBoolean selection: {bool_selection}")

Original array:
 [[38 28 14 42  7]
 [20 38 18 22 10]
 [10 23 35 39 23]
 [ 2 21  1 23 43]]

Boolean selection: [38 42 38 35 39 43]


In [24]:
# Modify the first element of the new array
bool_selection[0] = 999
print(f"Modified selection: {bool_selection}")

Modified selection: [999  42  38  35  39  43]


In [25]:
# The original array remains unchanged
print("Original array after modifying the copy:\n", arr)

Original array after modifying the copy:
 [[38 28 14 42  7]
 [20 38 18 22 10]
 [10 23 35 39 23]
 [ 2 21  1 23 43]]



---

**Next:** [Vectorized Operations and ufuncs](./06_vectorized_operations_and_ufuncs.ipynb)