# Vectorized Operations and Universal Functions

---

### Table of Contents
1. What is Vectorization?
2. Element-wise Arithmetic Operations
3. Universal Functions (ufuncs)
4. Conditional Logic with `np.where()`

---

## 1. What is Vectorization?
- Vectorization is the process of applying an operation to an entire array at once,
  rather than element by element in a Python loop.
- This is the core reason for NumPy's speed. The loops are executed in fast,
  pre-compiled C code instead of slower, interpreted Python.
- We saw a practical demo of this in the first lesson.

---

## 2. Element-wise Arithmetic Operations
- Standard arithmetic operators work element-wise on NumPy arrays.
- The arrays must have the same shape or be "broadcastable" (topic of the next lesson).

In [1]:
import numpy as np

# Create two sample arrays of the same shape
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([[10, 20, 30], [40, 50, 60]])

print("Array 1:\n", arr1)
print("Array 2:\n", arr2)

Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[10 20 30]
 [40 50 60]]


In [2]:
# --- Operations between two arrays ---

print("\nArray 1 + Array 2:\n", arr1 + arr2)
print(
    "\nArray 1 * Array 2:\n", arr1 * arr2
)  # Note that this is element-wise multiplication, not matrix multiplication.



Array 1 + Array 2:
 [[11 22 33]
 [44 55 66]]

Array 1 * Array 2:
 [[ 10  40  90]
 [160 250 360]]


In [3]:
# --- Operations with a scalar (a single number) ---

# This is a simple form of broadcasting.
print("\nArray 1 * 3:\n", arr1 * 3)
print(
    "\n1 / Array 1 (as float):\n", 1 / arr1.astype(float)
)  # Convert to float to see fractions
print("\nArray 1 ** 2 (squared):\n", arr1**2)


Array 1 * 3:
 [[ 3  6  9]
 [12 15 18]]

1 / Array 1 (as float):
 [[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]

Array 1 ** 2 (squared):
 [[ 1  4  9]
 [16 25 36]]



---

## 3. Universal Functions (ufuncs)
- A ufunc is a function that performs fast, element-wise operations on `ndarray` objects.
- The arithmetic operators we used are actually convenient wrappers for ufuncs.
  (e.g., `+` is a shortcut for `np.add`).


In [4]:
arr = np.arange(1, 10).reshape(3, 3)
print("Original array for ufuncs:\n", arr)

Original array for ufuncs:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
# --- Unary ufuncs (operate on one array) ---

print("\nSquare root (`np.sqrt`):\n", np.sqrt(arr))
print("\nExponential e^x (`np.exp`):\n", np.exp(arr))
print("\nNatural logarithm (`np.log`):\n", np.log(arr))


Square root (`np.sqrt`):
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]

Exponential e^x (`np.exp`):
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Natural logarithm (`np.log`):
 [[0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947]
 [1.94591015 2.07944154 2.19722458]]


In [6]:
# --- Binary Ufuncs (operate on two arrays) ---

# These are the explicit function calls for the operators we saw earlier
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 2, 6])
print(f"\nArray A: {arr_a}")
print(f"Array B: {arr_b}")
print(f"Element-wise maximum (`np.maximum`): {np.maximum(arr_a, arr_b)}")
print(f"Element-wise addition (`np.add`): {np.add(arr_a, arr_b)}")


Array A: [1 2 3]
Array B: [4 2 6]
Element-wise maximum (`np.maximum`): [4 2 6]
Element-wise addition (`np.add`): [5 4 9]



---

## 4. Conditional Logic with `np.where()`
- `np.where()` is the vectorized equivalent of a ternary expression (`x if condition else y`).
- It's a powerful tool for creating a new array based on a condition.
- Syntax: `np.where(condition, value_if_true, value_if_false)`

In [7]:
# Create a sample 3x3 array with random positive and negative numbers
np.random.seed(42)
data = np.random.randn(3, 3)

print("Original data:\n", data)

Original data:
 [[ 0.49671415 -0.1382643   0.64768854]
 [ 1.52302986 -0.23415337 -0.23413696]
 [ 1.57921282  0.76743473 -0.46947439]]


In [8]:
# Create a new array, replacing positive values with 1 and non-positive values with -1
# The condition `data > 0` produces a boolean array mask.
result = np.where(data > 0, 1, -1)
print("\nResult of `np.where(data > 0, 1, -1)`:\n", result)


Result of `np.where(data > 0, 1, -1)`:
 [[ 1 -1  1]
 [ 1 -1 -1]
 [ 1  1 -1]]


In [9]:
# It can also be used to selectively choose values from two other arrays
arr_positives = np.full_like(data, 100)  # Array full of 100s
arr_negatives = np.full_like(data, -100)  # Array full of -100s
selective_result = np.where(data > 0, arr_positives, arr_negatives)
print("\nResult of selecting from two other arrays:\n", selective_result)


Result of selecting from two other arrays:
 [[ 100. -100.  100.]
 [ 100. -100. -100.]
 [ 100.  100. -100.]]



---

**Next:** [Broadcasting](./07_broadcasting.ipynb)