# Stacking and Splitting Arrays

---

### Table of Contents
1. Introduction
2. Stacking Arrays (Joining)
3. Splitting Arrays

---

## 1. Introduction
- In data analysis, it's common to combine multiple datasets or
  split a single dataset into parts (e.g., for training and testing)
- NumPy provides several straightforward functions for stacking (joining)
  and splitting arrays.

In [1]:
import numpy as np

# --- Create two sample arrays to work with ---
np.random.seed(42)
arr1 = np.random.randint(10, size=(2, 3))  # A 2x3 array
arr2 = np.random.randint(10, size=(2, 3))  # Another 2x3 array

print("--- Sample Arrays ---")
print("Array 1:\n", arr1)
print("\nArray 2:\n", arr2)

--- Sample Arrays ---
Array 1:
 [[6 3 7]
 [4 6 9]]

Array 2:
 [[2 6 7]
 [4 3 7]]



---

## 2. Stacking Arrays (Joining)
- Combining multiple arrays into a single, larger one.

### 2.1. `np.vstack()` (Vertical Stack)
- Stacks arrays on top of each other (row-wise).
- The arrays must have the same number of columns.

In [2]:
v_stacked = np.vstack((arr1, arr2))

print("--- Stacking Arrays ---")
print("Vertically stacked (vstack):\n", v_stacked)
print("Shape of vstacked array:", v_stacked.shape)  # (4, 3)

--- Stacking Arrays ---
Vertically stacked (vstack):
 [[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]]
Shape of vstacked array: (4, 3)


### 2.2. `np.hstack()` (Horizontal Stack)
- Stacks arrays next to each other (column-wise).
- The arrays must have the same number of rows.

In [3]:
h_stacked = np.hstack((arr1, arr2))
print("\nHorizontally stacked (hstack):\n", h_stacked)
print("Shape of hstacked array:", h_stacked.shape)  # (2, 6)


Horizontally stacked (hstack):
 [[6 3 7 2 6 7]
 [4 6 9 4 3 7]]
Shape of hstacked array: (2, 6)


### 2.3. `np.concatenate() (The General Method)`
- `vstack` and `hstack` are just convenient wrappers around `concatenate`.
- The `axis` parameter controls the direction of the join:
  - `axis=0`: Joins along the rows (like vstack).
  - `axis=1`: Joins along the columns (like hstack).

In [5]:
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
print("\nConcatenate with axis=0 (same as vstack):\n", concat_axis0)

concat_axis1 = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenate with axis=1 (same as hstack):\n", concat_axis1)


Concatenate with axis=0 (same as vstack):
 [[6 3 7]
 [4 6 9]
 [2 6 7]
 [4 3 7]]

Concatenate with axis=1 (same as hstack):
 [[6 3 7 2 6 7]
 [4 6 9 4 3 7]]



---

## 3. Splitting Arrays
- Breaking one large array into several smaller sub-arrays.

In [6]:
# --- Create a larger array to split ---

large_arr = np.arange(24).reshape(6, 4)  # A 6x4 array

print("Large array to be split (6x4):\n", large_arr)

Large array to be split (6x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


### 3.1. `np.vsplit()` (Vertical Split)
- Splits an array into multiple sub-arrays vertically (row-wise).

In [7]:
# Split into 3 equal sub-arrays:
v_split_equal = np.vsplit(large_arr, 3)  # returns a list of arrays
print("\nVertically split into 3 equal arrays:")
for arr in v_split_equal:
    print(f"{arr}\n---")


Vertically split into 3 equal arrays:
[[0 1 2 3]
 [4 5 6 7]]
---
[[ 8  9 10 11]
 [12 13 14 15]]
---
[[16 17 18 19]
 [20 21 22 23]]
---


In [8]:
# Split at specific rows.
# To split at rows at indices 1 and 3, use `[1, 3]`. This creates 3 sub-array:
v_split_unequal = np.vsplit(large_arr, [1, 3])
print("Vertically split at rows 1 and 3:")
for arr in v_split_unequal:
    print(arr, "\n--")

Vertically split at rows 1 and 3:
[[0 1 2 3]] 
--
[[ 4  5  6  7]
 [ 8  9 10 11]] 
--
[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 
--


### 3.2. `np.hsplit()` (Horizontal Split)
- Splits an array horizontally (column-wise).

In [9]:
# Split into 2 equal sub-arrays:
h_split_equal = np.hsplit(large_arr, 2)
print("Horizontally split into 2 equal arrays:")
for arr in h_split_equal:
    print(arr, "\n--")

Horizontally split into 2 equal arrays:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]
 [20 21]] 
--
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]
 [22 23]] 
--


### 3.3. `np.array_split()` (The General Method)
- `vsplit` and `hsplit` require the split to result in equal-sized arrays.
- `array_split` is more flexible and does NOT require equal splits.

In [10]:
uneven_arr = np.arange(7)
print(f"\nSplitting an uneven array: {uneven_arr}")

uneven_split = np.array_split(uneven_arr, 3)  # Split a 7-element array into 3 parts.
print("Result of `array_split`:")
for arr in uneven_split:
    print(arr)


Splitting an uneven array: [0 1 2 3 4 5 6]
Result of `array_split`:
[0 1 2]
[3 4]
[5 6]



---

**Next:** [Statistical Methods](./10_statistical_methods.ipynb)