# Statistical Methods

---

### Table of Contents
1. Introduction to Aggregations
2. Basic Aggregate Functions
3. The `axis` Parameter (The Key Concept)
4. Other Useful Statistical Functions

---

## 1. Introduction to Aggregations
- Aggregation is the process of reducing an array to a single summary value
  (e.g., the sum, mean, or standard deviation).
- NumPy aggregation functions are very fast and are a cornerstone of data analysis.

In [1]:
import numpy as np

# Create a sample 2-D array for our examples
np.random.seed(0)
arr = np.random.randint(0, 20, size=(3, 5))  # A 3x5 array of random ints from 0 to 19

print("--- Sample Array ---")
print(arr)

--- Sample Array ---
[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]]



---

## 2. Basic Aggregate Functions
- These functions can be called as methods on an array object (`arr.sum()`)
  or as top-level NumPy functions (`np.sum(arr)`).
- By default, they operate on the entire array.

In [2]:
# Sum of all elements
print(f"Sum of all elements: {arr.sum()}")

Sum of all elements: 122


In [3]:
# Mean (average) of all elements
print(f"Mean of all elements: {arr.mean():.2f}")

Mean of all elements: 8.13


In [4]:
# Standard deviation (a measure of spread)
print(f"Standard deviation: {arr.std():.2f}")

Standard deviation: 5.73


In [5]:
# Variance (the square of the standard deviation)
print(f"Variance: {arr.var():.2f}")

Variance: 32.78


In [6]:
# Minimum and maximum values
print(f"Minimum value: {arr.min()}")
print(f"Maximum value: {arr.max()}")

Minimum value: 0
Maximum value: 19



---

## 3. The `axis` Parameter (The Key Concept)
- The `axis` parameter allows you to perform aggregations along a specific dimension.
- For a 2-D array (a matrix):
  - `axis=0`: Aggregates "down the columns". Collapses the rows.
  - `axis=1`: Aggregates "across the rows". Collapses the columns.

In [7]:
print("Original array:\n", arr)

Original array:
 [[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]]


In [9]:
# --- Summing along axes ---

# Sum down the columns (axis=0) -> results in 1 value for each column
col_sums = arr.sum(axis=0)
print(f"\nSum of each column (axis=0): {col_sums}")
print(f"Shape of the result: {col_sums.shape}")

# Sum across the rows (axis=1) -> results in 1 value for each row
row_sums = arr.sum(axis=1)
print(f"\nSum of each row (axis=1): {row_sums}")
print(f"Shape of the result: {row_sums.shape}")


Sum of each column (axis=0): [25 36 20 27 14]
Shape of the result: (5,)

Sum of each row (axis=1): [33 57 32]
Shape of the result: (3,)


In [10]:
# --- Finding the max value along axes ---

col_max = arr.max(axis=0)
print(f"\nMax value in each column (axis=0): {col_max}")

row_max = arr.max(axis=1)
print(f"\nMax value in each row (axis=1): {row_max}")


Max value in each column (axis=0): [12 15 19 18  7]

Max value in each row (axis=1): [15 19 12]



---

## 4. Other Useful Statistical Functions

### 4.1. Cumulative Sum (`.cumsum()`)

In [15]:
arr_1d = np.arange(5)
print(f"1-D array: {arr_1d}")
print(f"Cumulative sum of 1-D array: {arr_1d.cumsum()}")

1-D array: [0 1 2 3 4]
Cumulative sum of 1-D array: [ 0  1  3  6 10]


In [16]:
# It also works along axes
print(f"\nCumulative sum down columns (axis=0):\n{arr.cumsum(axis=0)}")


Cumulative sum down columns (axis=0):
[[12 15  0  3  3]
 [19 24 19 21  7]
 [25 36 20 27 14]]


### 4.2. `argmin` and `argmax`
 - These find the *index* of the minimum or maximum element, not the value itself.

In [17]:
print(f"\nOriginal array:\n{arr}")
print(f"Index of the minimum value in the flattened array: {arr.argmin()}")
print(f"Index of the maximum value in each column (axis=0): {arr.argmax(axis=0)}")


Original array:
[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]]
Index of the minimum value in the flattened array: 2
Index of the maximum value in each column (axis=0): [0 0 1 1 2]


### 4.3. `np.percentile()`
- Computes the q-th percentile of the data. This is a function, not a method.
- The 50th percentile is the median.

In [18]:
print(
    f"\nThe 50th percentile (median) of the entire array is: {np.percentile(arr, 50)}"
)
print(f"The 90th percentile of the entire array is: {np.percentile(arr, 90):.2f}")


The 50th percentile (median) of the entire array is: 7.0
The 90th percentile of the entire array is: 16.80



---

**Next:** [Linear Algebra with NumPy](./11_linear_algebra_with_numpy.ipynb)